AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Parking Lot Management System

Resources:
  ParkingLotEntryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: entry.lambda_handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: ParkingLotTickets
      Events:
        EntryApi:
          Type: Api
          Properties:
            Path: /entry
            Method: post

  ParkingLotExitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: exit.lambda_handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: ParkingLotTickets
      Events:
        ExitApi:
          Type: Api
          Properties:
            Path: /exit
            Method: post

  ParkingLotTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ParkingLotTickets
      AttributeDefinitions:
        - AttributeName: ticketId
          AttributeType: S
      KeySchema:
        - AttributeName: ticketId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST 

Outputs:
  ApiUrl:
    Description: "Base URL for API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"